[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Probe rs is used when debug prob ued
# runner = "probe-rs run --chip RP2040"
# Generate uf2 using elf2uf2-rs 
runner = "elf2uf2-rs"

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"
